import 'package:blog_app/core/common/cubits/app_user/app_user_cubit.dart';
import 'package:blog_app/core/network/connection_checker.dart';
import 'package:blog_app/core/secrets/app_secrets.dart';
import 'package:blog_app/features/auth/data/datasources/auth_remote_data_source.dart';
import 'package:blog_app/features/auth/data/repository/auth_repository_impl.dart';
import 'package:blog_app/features/auth/domain/repository/auth_repository.dart';
import 'package:blog_app/features/auth/domain/usercases/current_user.dart';
import 'package:blog_app/features/auth/domain/usercases/user_login.dart';
import 'package:blog_app/features/auth/domain/usercases/user_sign_up.dart';
import 'package:blog_app/features/auth/presentation/bloc/auth_bloc.dart';
// import 'package:blog_app/features/blog/data/datasources/blog_local_data_source.dart';
import 'package:blog_app/features/blog/data/datasources/blog_remote_data_source.dart';
import 'package:blog_app/features/blog/data/repositories/blog_repository_impl.dart';
import 'package:blog_app/features/blog/domain/repositories/blog_repository.dart';
import 'package:blog_app/features/blog/domain/usecases/delete_blog.dart';
import 'package:blog_app/features/blog/domain/usecases/delete_user_account.dart';
import 'package:blog_app/features/blog/domain/usecases/follow_user.dart';
import 'package:blog_app/features/blog/domain/usecases/ger_user_profile.dart';
import 'package:blog_app/features/blog/domain/usecases/get_all_blogs.dart';
import 'package:blog_app/features/blog/domain/usecases/get_favorite_blogs.dart';
import 'package:blog_app/features/blog/domain/usecases/get_follow_count.dart';
import 'package:blog_app/features/blog/domain/usecases/get_next_blog.dart';
import 'package:blog_app/features/blog/domain/usecases/get_user_blogs.dart';
import 'package:blog_app/features/blog/domain/usecases/is_following.dart';
import 'package:blog_app/features/blog/domain/usecases/logout_user.dart';
import 'package:blog_app/features/blog/domain/usecases/toggle_favorite.dart';
import 'package:blog_app/features/blog/domain/usecases/unfollow_user.dart';
import 'package:blog_app/features/blog/domain/usecases/update_blog.dart';
import 'package:blog_app/features/blog/domain/usecases/update_user_profile.dart';
import 'package:blog_app/features/blog/domain/usecases/upload_blog.dart';
import 'package:blog_app/features/blog/presentation/bloc/blog/blog_bloc.dart';
import 'package:blog_app/features/blog/presentation/bloc/profile/profile_bloc.dart';
import 'package:blog_app/features/blog/presentation/cubit/blog_navigation_cubit.dart';
import 'package:get_it/get_it.dart';
// import 'package:hive/hive.dart';
import 'package:internet_connection_checker_plus/internet_connection_checker_plus.dart';
// import 'package:path_provider/path_provider.dart';
import 'package:supabase_flutter/supabase_flutter.dart';

part 'init_dependencies.main.dart';